// <auto-generated />
using System;
using JobApplicationTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApplicationTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("JobApplicationTracker.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataApplied")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Tech Solutions",
                            DataApplied = new DateTime(2025, 8, 5, 15, 25, 30, 183, DateTimeKind.Local).AddTicks(6486),
                            JobTitle = "Software Engineer",
                            Notes = "Initial application submitted.",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Innovatech",
                            DataApplied = new DateTime(2025, 8, 10, 15, 25, 30, 185, DateTimeKind.Local).AddTicks(9775),
                            JobTitle = "Data Analyst",
                            Notes = "Interview scheduled for next week.",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Global Corp",
                            DataApplied = new DateTime(2025, 7, 31, 15, 25, 30, 185, DateTimeKind.Local).AddTicks(9781),
                            JobTitle = "Project Manager",
                            Notes = "Received offer letter, pending decision.",
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
